import { Em } from './em';
import { Rnr } from './rnr';
import { Spr } from './spr';
import { Ins } from './ins';
import { Par } from './par';
export class Account {
  id: number;
  name: string;
  TBL: string;
  GUID: string;
  TS_CREATION: string;
  KDNR: string;
  KDNR_NEW: string;
  SO_ACTIVATION: string;
  STATUS: string;
  SYSTEL: string;
  TO_NR: string;
  TS_LAST_UPDATE: string;
  TS_LAST_PROV_EM: string;
  TS_LAST_PROV_PARAM: string;
  TS_LAST_PROV_RUFNR: string;
  TS_LAST_PROV_SPERRE: string;
  KDNR_OLD: string;
  ACCOUNT_TYPE_ID: number;
  LAST_UPD: string;
  emlist: Em[];
  emselected: Em;
  rnrlist: Rnr[];
  rnrselected: Rnr;
  sprlist: Spr[];
  sprselected: Spr;
  inslist: Ins[];
  insselected: Ins;
  parlist: Par[];
  parselected: Par;
}